--조인
CREATE TABLE A(
	CODE CHAR(1),
	VAL NUMBER(1)
);
CREATE TABLE B(
	CODE CHAR(1),
	UNIT CHAR(1)
);

INSERT INTO A VALUES('A',1);
INSERT INTO A VALUES('B',2);
INSERT INTO A VALUES('C',3);
INSERT INTO A VALUES('D',4);

INSERT INTO B VALUES('A','+');
INSERT INTO B VALUES('B','-');
INSERT INTO B VALUES('C','*');
INSERT INTO B VALUES('F','/');

--동일 조인
SELECT A.CODE, A.VAL, B.CODE, B.UNIT 
FROM A, B
WHERE A.CODE = B.CODE;

--자연 조인
SELECT * FROM A NATURAL JOIN B;

--교차 조인
SELECT * FROM A CROSS JOIN B;

--행번호
SELECT ROWNUM, CODE, VAL FROM A;

--학과 목록
SELECT DISTINCT STD_MAJOR FROM STUDENT;

--테이블 생성
CREATE TABLE TEST
AS
SELECT ROWNUM AS RN, CODE, VAL FROM A;

--1. 학과 테이블을 학생 테이블로 부터 뽑아서 저장, 학과번호는 행번호로 지정
CREATE TABLE MAJOR
AS
SELECT ROWNUM AS MAJOR_NO, MAJOR_NAME
FROM
(SELECT DISTINCT STD_MAJOR AS MAJOR_NAME  FROM STUDENT);
-- 기본키 추가 - MAJOR_NO
ALTER TABLE MAJOR ADD CONSTRAINT MAJOR_PK PRIMARY KEY(MAJOR_NO);

--2. 학생 테이블에 학과 번호 컬럼 추가
ALTER TABLE STUDENT ADD MAJOR_NO NUMBER;

--3. 학생 테이블에 학과번호 업데이트 후 학과명을 삭제  
UPDATE STUDENT 
SET MAJOR_NO = (SELECT MAJOR_NO FROM MAJOR WHERE MAJOR_NAME = STD_MAJOR);

ALTER TABLE STUDENT DROP COLUMN STD_MAJOR;








