-- 함수
CREATE OR REPLACE FUNCTION GET_MAJAOR_NAME(IN_MAJOR_NO IN NUMBER)
RETURN VARCHAR2
IS
    --사용할 변수 선언
    NAME VARCHAR2(50);
BEGIN
    --조회된 결과를 변수 NAME에 저장
    SELECT MAJOR_NAME INTO NAME FROM MAJOR WHERE MAJOR_NO = IN_MAJOR_NO;
    RETURN NAME;
END;
SELECT GET_MAJAOR_NAME(2) FROM DUAL;

CREATE OR REPLACE FUNCTION GET_ODD_EVEN(N IN NUMBER)
RETURN VARCHAR2
IS
    MSG VARCHAR2(100);
BEGIN
    IF N = 0 THEN
        MSG := '0입이니다.';
    ELSIF MOD(N,2) = 1 THEN
        MSG := '홀수 입니다.';
    ELSE
        MSG := '짝수입니다.';
    END IF;
    RETURN MSG;
END;

SELECT get_odd_even(3) FROM DUAL;






