CREATE TABLE BOARD_MEMBER(
	MEMBER_ID VARCHAR2(30),
	MEMBER_PASSWD CHAR(128),
	MEMBER_NAME VARCHAR2(30),
	MEMBER_NICK VARCHAR2(30)	
);

CREATE TABLE BOARD(
	BOARD_NO NUMBER,
	BOARD_TITLE VARCHAR2(300),
	BOARD_CONTENT VARCHAR2(3000),
	BOARD_WRITE_TIME DATE DEFAULT SYSDATE,
	BOARD_COUNT NUMBER,
	MEMBER_ID VARCHAR2(30)
);

CREATE TABLE BOARD_LIKE(
	BOARD_NO NUMBER,
	MEMBER_ID VARCHAR2(30)
);

CREATE TABLE BOARD_HATE(
	BOARD_NO NUMBER,
	MEMBER_ID VARCHAR2(30)
);







